### ISSUE TITLE
make a website!

### ISSUE THREAD

**Issue by lislis** [rubycorns/rubycorns.club#1]
So people interested!

To make this work we need
- [ ] a design
- [ ] content

Content-wise I think it would suffice to:
-  say who we are
- what we're working on
- link to our email address/ mailing list
- link to our twitter
- link to github
- link to rorganize.it  

Maybe add a little blog thing. I mean, this is jekyll after all.

Design-wise I'd like to include the ascii-corn in red and combine that with a dark-ish background.

Thoughts, ideas, opinions, suggestions?

**Comment by berlintam** [comment]
aside from the blog, looks like this is totes done!

**Comment by sareg0** [comment]
yeah, is this one ready to close up now? or do we still need to add some stuff?
